name: Auto Sync to MineBBS

on:
  release:
    types: [published]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Package Plugin ZIP
        run: |
          zip -r YEssential.zip . \
            --exclude "*.git*" \
            --exclude ".github/*" \
            --exclude "upload.js" \
            --exclude "README.md"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install axios cheerio form-data qs

      - name: Run Sync Script
        env:
          MINEBBS_COOKIE: ${{ secrets.MINEBBS_COOKIE }}
          MINEBBS_TARGET_URL: 'https://www.minebbs.com/resources/yessential-home-warp-tpa-money-menu-cleanitem.10332/post-update'
          MINEBBS_FILE_PATH: './YEssential.zip'
          MINEBBS_VERSION: ${{ github.event.release.tag_name }}
          MINEBBS_UPDATE_TITLE: 'GitHub 同步: ${{ github.event.release.name }}'
          MINEBBS_CHANGE_LOG: ${{ github.event.release.body }}
        run: node upload.js
